import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { getLocale, getMessages } from "next-intl/server";
import { NextIntlClientProvider } from "next-intl";
import StoreProvider from "@/redux/StoreProvider";
import Navigation from "@/components/navigation/Navigation";
import { colors } from "@/layout";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const messages = await getMessages();
  const locale = await getLocale();

  return (
    <html lang={locale}>
      <NextIntlClientProvider messages={messages}>
        <StoreProvider>
          <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased w-screen overflow-x-hidden`}
          >
            <Navigation />
            {children}
          </body>
        </StoreProvider>
      </NextIntlClientProvider>
    </html>
  );
}
